name: Shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest 
    steps:
      - name: echo a string
        run: echo "Hello my World"
      - name: multiline script
        run: |
          node -v
          npm -v
  runs-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Powershell Directory
        run: Get-Location
      - name: Bash Directory
        run: pwd       
        shell: bash   