name: Shell commands
on: [push]
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest 
    steps:
      - name: echo a string
        run: echo "Hello my World"
      - name: multiline script
        run: |
          node -v
          npm -v